services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: rifqy_de
      POSTGRES_PASSWORD: purwade12345
      POSTGRES_DB: module1-capstone-project
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql